apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-docker-registry
  namespace: argocd
  finalizers:
    - resources-finalizer.argoproj.io
spec:
  project: wywy-dev
  source:
    repoURL: https://github.com/WywySenarios/Wywy-Website-Control.git
    targetRevision: main
    path: k8s/dev/docker-registry
  destination:
    server: https://kubernetes.default.svc
    namespace: github-runner
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
