apiVersion: v1
kind: Secret
metadata:
    name: migrator-password
    namespace: master-database
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:WdLZ7azL6hWeSpRGwqs3zLnRgqxePrAJ,iv:5Uj695QTn8JxqoTe6wXr9OFyUKYEyJtzbunfjURtFAI=,tag:KuilOZNQQx1oFDxcZ6Baow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM3IwZzNiVnF1UFFDTkta
            VWdLSEwyNkNJQ041anJDek5ZUEx3cURxbkZrClJpSTJwZ2syNVEyK3JoS01hcmU3
            RjE5ZWw4TVlqanhTbGloVWpObGpTOHMKLS0tIFRyd0wvYU1LaWdFeWJlT0hlSzN5
            KzhUQlovcnJHRGhmdTMxMG8vUHQ3aVEKKVjLBeM3zTKSjHHps7yqPFAT5hsHhMVM
            1OyXFZT8uPEpphPUNVaM+Ly2zRHExNdsJ6pdAZwXNlZmXOpfxOrFgg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19rz07h4nrfarqdm5fwucwj8024w2el04ak39nwrmdvjypjgukpsst5dmar
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T21:47:21Z"
    mac: ENC[AES256_GCM,data:KDpjanT0jBADgt5d00Mv2U66eMVL5SJNGeOqwvFr6qYEkqtrAuQLchn6r/Kd4mBP6/YMmga3y45jjxEA+31qwo2rEqm8M0Kd/ciDvDqyJ4nfdQ/ZqjnXQChH2SDPMXMJxfA1/cynYA7+GxD9/k/7EQhI24VkvRuGVmO92VszyWg=,iv:nnXDvIKyyGyHuMU9vX113APsLAeqqyaPybsvZcQItVY=,tag:gks53EKLk6u+AKi3BXcKaA==,type:str]
    version: 3.13.2
