apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: master-database-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - master-db-admin.sops.yaml
  - postgres-password.sops.yaml
  - regcred.sops.yaml
