apiVersion: v1
kind: Secret
metadata:
    name: master-db-admin
    namespace: master-database
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:BKzuFuGLHYZHjjNPpn9sh/rS0zWyTICZ,iv:IhEHBa/ht32xSW52vge2XHr0qERK4Nmr9vRlqtfU10w=,tag:rvYIzKXa7RhGkmpL5bwClA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cmdWbWRHTUx3VVRubGhk
            RVljUE1BNFJRQ0ZXeHZNZlhPcTZ4Y2Q5MDFnCjczbHphRm1hYk13NzJrZEhKYmZW
            dWJqa3IveDFNbTFiZ2J3OTRhTXpnMGsKLS0tIFdjMFQ0dG01VG0rUTI5Z1dPTmRB
            bjFNRXJrTGxoaFpvUVBPWWtnTE9qcEkKHpDLPCG3fmeTIwlV/ib0SdgBAqMu6Hhx
            +4oFRGZK36X9dWS89ElwtNzaN90cS1LSNetiApCqqIoerw6fWKOBDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19rz07h4nrfarqdm5fwucwj8024w2el04ak39nwrmdvjypjgukpsst5dmar
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T00:33:33Z"
    mac: ENC[AES256_GCM,data:zlIWZ92WwOPbRxMVCTCOGoCddGZKxCpyfo5FutYxE7Gb9zn3cKbth5HQOuDw49W+p2pSODHpvdMrReQYNCzuJdbcGgwwb8j4zW3HmuGJl2KhKrkvTmvmEqVxyQSG8PaxSkepYnVLolBndTPN+N7jZE1pzCP3/wP2XaS2AeR4sFc=,iv:jC6v94EuiLr9JyZ3KreqI1RAFCYRVOMpywazyVexg/g=,tag:8GGn3xT6Gn95cxf3xSCbJg==,type:str]
    version: 3.13.2
