apiVersion: v1
kind: Secret
metadata:
    name: migrator-password
    namespace: master-database
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:a/Do8v+O7lNJQWqYzeUG8PuO+j7ktr+W,iv:BxPJ+NcO7/Kywr1zpSzgE4QUAPqt7rrdxhvgIPPqZpA=,tag:Yek3xc+iaTgogBJnTtHjsw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiR28yRWJFTUVyeCtocDNp
            NTBIWm1pWjQ1YkE1MDFkSHZtZGRVZ3pZcVJRCkc4eHRCNTFncTg2YkU1NVM0b3Fj
            eGNEWnJnZXRaM0dDeCszTm9DcG0ybUEKLS0tIGpJNiswbVc5b0FjbUJtOXFIamEy
            SSsvTkNLaDlUMFNzYmV2N0VPejAxRzQKBOE9NrjtCznbNhY6HhzQ0H4PjkVi3E1f
            o6Dnb1VMln9/aumh7ODvtNlp2xaV16e0sYoqNTbvu0zDuYS9T1nLsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19rz07h4nrfarqdm5fwucwj8024w2el04ak39nwrmdvjypjgukpsst5dmar
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T21:45:32Z"
    mac: ENC[AES256_GCM,data:LmEko2Y+Fm+YG6kZLeCEq2oTYKNk6syPCZasFEp1HTNiJDAfGFhzKVB4imQbLsrkT5R5bh08l6J2cfQLBnRuo5DJ2H90lZ5+pF37t3My/novyNxcPLen771Wqi4py+HT/wMPPHf71vGLfGHpYszGzg7HoCFceP6LZg4XtoWNfS4=,iv:io+yJVpECWCtKFtXQIgyn4n9yWFDbGcp9rO2P0kpe/I=,tag:fmlcpcIto0MCxzn9FxErsA==,type:str]
    version: 3.13.2
