apiVersion: v1
kind: Secret
metadata:
    name: postgres-password
    namespace: master-database
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:NYYokdIU2YppS8BW2RG9mfljxmCqTaK+jz21kARvG7TkxX2F9g==,iv:WUbOO8CpXaD9v6P4AmICs/jd3npn+LS55eNhCz2ur4o=,tag:7RVy4JvRTC6mYtOskBevIw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bHluTFVHQkJrR1ZmYkZS
            YmpFbGNoK0hhK0N2OTczaEc3TnZZdEZOUzBvCnBvK01JSVg2TkV3Y0c3bVRUUEhv
            UzZvYlFlY21WajBObEl1anNsQmI0VlUKLS0tIHh4blpzYmt0VGkwa3p2SlZva08z
            ZFlsRmRPTFhreHovQVpTYXExMVplbTgKyljomKjjJBq/eiJRaKCKgD8xUop5NmJw
            ub0MqZAGvAoZNnFBQN7O9nKt1l6BX+5PZro75kTZyrfsc6E/JWbZ0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19rz07h4nrfarqdm5fwucwj8024w2el04ak39nwrmdvjypjgukpsst5dmar
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T00:33:33Z"
    mac: ENC[AES256_GCM,data:l5CNQ6ava/pooy+ZI2p6w4E9awkM8puICpkpw9+hIqGHbFqLSuDc144hlrsU8cWIrf7Xr+lHy0dEExOAEjZ9ryDNZpfPlVAVj4/bLCvp+3D916kbNtMXG6Bw3sKN0Ttkr5ZlwxSzUTkVE4M1WEM+/4eTHtaVZyep7WF53X/QXBI=,iv:4nY6pEwxFz2Tusp3xEu3WtXdlcXMOfy4CcM4DuJHdiQ=,tag:IDkid9BYWu2XbmWjvWOdjA==,type:str]
    version: 3.13.2
