apiVersion: v1
kind: Secret
metadata:
    name: regcred
    namespace: master-database
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:bC5CgHg/5mvqy4o1YouDLHyrnpy1hhwe8SFVyLoms3m0/ywKh2dsphBntmGFW9P+QlKXJCTKgZ5k722LssLoImHWn39w+lrpIkveYZkpdmM2bok0jVHMnH2C1wupjKTIDDvxVLFP1pDGPcna9s+coyJf,iv:BhVSQETMZjwXXa13Z3kpkUFfTXYulaNQHdy47kQx5og=,tag:iC5mXZSHKs6QP8K6huUgGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWW1vN29UZ1Z3cnpNNEEy
            NGJaa05oQjJhNXJQZ2VyWlNkSzkwMWJjdno0CkVUSnFxMHcxY1k0eDRVUDFoRUdP
            SjkxT1hkRm1kRmhxQWQ1M3NuVWcvNDQKLS0tIGtnZmpXRHAxQkNLaDRPNjljSy8z
            WkxTWVhaQ2ZRdFo3VHNMVnRldkRXcUkKnIhXI1W8vjPbPaZA9nTTs6GwNqIx1cBT
            6wyj3HulfLtd3uG6oZ81huvOULMk8/p1rLjJ1b+IZf5f0bXlnm8MiQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19rz07h4nrfarqdm5fwucwj8024w2el04ak39nwrmdvjypjgukpsst5dmar
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T00:33:33Z"
    mac: ENC[AES256_GCM,data:sSLXkXj5VhHt89SuC3EzgEfPm7VTxcrH9ufN8I1iue02XPC28YzaT+9T0a91A/hvjAGz6b6NHFgF7t4nuRuqMhIftGa3201iWW4vKLI0uwqHIke9W/NipRGvEOidLFbC3DSL/MQHHIu++jhYtQ5sHXU1cmgDJ9JWBTIpME9REqU=,iv:yohZf44hRd2qfFy2QDkoahl4sK5sk3jjaLbzxH+mM0I=,tag:KnfwKUZDQbRWLwUtNTvGfQ==,type:str]
    version: 3.13.2
