apiVersion: v1
kind: Secret
metadata:
    name: github-runner-pat
    namespace: github-runner
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:I873bbm9UZFu4esqUWz+jEaI+TlADIolIp+HBZqeyS+5jw3wmuPycQ==,iv:CP2r0fU/7CEm4jqwtVjmJlq8PVQJyrgeCuGVuAaSie8=,tag:q8r7QwTZHhu34RvovR4PIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZ0ROWFE0Y0FjZHMwbDEy
            UldMWDNUMnVsYlBwWHRhRzVkZis4ZjNUcWpnClJEalFoVHp4angzeTFlcGZsUXky
            RGZvNkpUR0V4UWd2YWZaaFJXS2Q0OEkKLS0tIHp3K0poRmFCeks5QmZialdPa1ZP
            VnhrbDVta1h4TEVlME9UYTF1NnFWTDAKljd2nXdfJEams+uLnegJsZLeNG7s/Taz
            BTMGRYfiUtKn3l9hOY1Clq1C27hJtxzts87tZMV5mOMPoy+4VadXVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19rz07h4nrfarqdm5fwucwj8024w2el04ak39nwrmdvjypjgukpsst5dmar
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T02:16:56Z"
    mac: ENC[AES256_GCM,data:jo3SnJlXRfEkiSE2Cm60U5VdTvAATCA10f+J+5ULo0IN0rZLJnZZjhrPz9gLkQLs3QJh+WSfYAKN9LiIq4KE28zpfzG2SgptA84XQIoWnr0hO2gIEpQGijqFLHzuPmA8pfTkonjh1ZYk7H3w29StA+hwyFGfFhW1HRZpT06a6mo=,iv:ywVy8I8ClF2V4xAOK4QxEbTcZuUWogJwWxZvUGsyYGQ=,tag:/y8/onf/ez6MCYHGKNi5Tg==,type:str]
    version: 3.13.2
