apiVersion: v1
kind: Secret
metadata:
    name: github-runner-pat
    namespace: github-runner
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:zqUtBgjV672ejmOxxmTp20itfkcydsvnWvpEwJ6iEmBxKi/nlbv4xaoEFsELZraEzvWLJcFhepmxYjjiUOc=,iv:yZKwB2iVS3fxLH0wFRsQsgmgoynAJYavDB8C3fQc5Ck=,tag:uvRrCr4n/S2dLUoeGQlGRA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZ0ROWFE0Y0FjZHMwbDEy
            UldMWDNUMnVsYlBwWHRhRzVkZis4ZjNUcWpnClJEalFoVHp4angzeTFlcGZsUXky
            RGZvNkpUR0V4UWd2YWZaaFJXS2Q0OEkKLS0tIHp3K0poRmFCeks5QmZialdPa1ZP
            VnhrbDVta1h4TEVlME9UYTF1NnFWTDAKljd2nXdfJEams+uLnegJsZLeNG7s/Taz
            BTMGRYfiUtKn3l9hOY1Clq1C27hJtxzts87tZMV5mOMPoy+4VadXVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19rz07h4nrfarqdm5fwucwj8024w2el04ak39nwrmdvjypjgukpsst5dmar
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T23:21:55Z"
    mac: ENC[AES256_GCM,data:9DwmPnKlV8R9y0rWlIFNLa2fgO4+4xphcOXRd6e3LBFxLVZOqxrlT4cpCI9toY7Kc2ZOS/kIzuS9qOrWHDQrYGotYfAakp+qAv5H9kHRMUstr45Z07o5BeXH9LlyltjQnOT07s3QbI9cEXw63ZHPt8mvqzPWwh4G5zRS6NOM8PY=,iv:B+av85mxE1/12bcEQ1O8BNr9+gPrA+RGRJJNYhAz2Bs=,tag:hLCWtbyfGroDLdpgeIq5uA==,type:str]
    version: 3.13.2
