apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: dev-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - registry-auth.sops.yaml
  - github-runner-pat.sops.yaml
  - regcred-ghcr.sops.yaml
