apiVersion: v1
kind: Secret
metadata:
    name: postgres-password
    namespace: github-runner
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:ussCDcVj6SwNc/1W2k41wmWfsnACDo/F,iv:yPjRPk3CgrnEsnwudR9Sf7MTqzitEisS9pPm4PwWH+4=,tag:P+i9mA4Xc1Vy8FeszfWLXQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Rm5PUEV6ckdFclpUcTND
            Rk5scmhFMkk2VE81YU42QzhvS0lwanhTblJ3Cmc5cDNEUlVYQTFTQWZ6dHNoQkNK
            WmJLQzdjZGFZNEdEWlp5NVE4ZmszNFkKLS0tIDhiYnZPYVlCMXkwMzVmdjgzMzFI
            SWJ4eVJjT3NWVDAzVmNycHJkMEdHU0UKXDffymLvKJ1zp9Sy8//TLSn1jmJJu/RW
            mE+vM6AezeNNHi+On7F+KtSHsUXtOuP6GwpKU3jjczooiwkztHNldg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19rz07h4nrfarqdm5fwucwj8024w2el04ak39nwrmdvjypjgukpsst5dmar
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T04:03:11Z"
    mac: ENC[AES256_GCM,data:CrtElKSKBX3imfviCEEU378l5wsW3EcqOQDc1WtNoJwDiBspuhd1MFcpj08BHNDLns5HBUKmClcqpjWBWGT1hGkjiZPqYd1Q2nyrVCR/Y27zZZZ43hilLUaItPSmk4iLETZsdycwCOn3JYfjzx9izXBMJAWRXlin8UwqUhz+d1E=,iv:briKMa/bhwGyATJdI0yIG+bI69d6oEeNUtxKJrl6fCw=,tag:kBCUrq2mX3sdNG+0yAFxWQ==,type:str]
    version: 3.13.2
