apiVersion: v1
kind: Secret
metadata:
    name: regcred-ghcr
    namespace: github-runner
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:VWWYhvfUinnMJkT3yXrQKCJMfRlXeQzF3Cuo73x1tnPrrFEnCC8CU0nLPdc8zHqnNtHoFcA/ezw9JtbJOa2TOoMMjmRGrX8DTWJZrjP5o2KBZBP+4/0qMUSZEQ/XqX2iaamH2ycQ4w==,iv:JRJhipfHBgFsm5FHZ0mBFQr4yaA/e8ekXRLojRSk42c=,tag:KB1kgfseyDyUoF/oMzXrmw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPME9DT0ZpQjBycXRZNnJJ
            bFpjYjB4aUJoTklTQm1UY3l1K0I4czhablFjCkk2bDgxUGdmbFhkN0JlN0NLVDFD
            bTFTTGI4ZVR6MTBtaHNzUUQvNjlQSEUKLS0tIGo0SDU1RlEvRkplSFRncDI0M2Nt
            MGU1QkU5Mk4yYVg0T25iakNJTkE0WHMKQuLZ5mGkXH1ev3ea5rcYpui7nFAquk2S
            7ayFzYl30RV59y5Nb5mleSMzXZmE46mk0Gxpc4YfcVxFld07whsBVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19rz07h4nrfarqdm5fwucwj8024w2el04ak39nwrmdvjypjgukpsst5dmar
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T02:54:39Z"
    mac: ENC[AES256_GCM,data:g6+gYDuTZTXoiFftFbOe2OeRbDVuT8wPC1SIbgcBX3eMXDE8HaKwj6rvv2HJJ0Vfxi1ouh9KSi2QjTwTOjn6csaojYrIL3iiWkAmvd+S2UNadAfxK2LWkEX/uejtQXrKWRPH2SUzndBirt1Cyi/Q8rcDxNjyD/tUMiTmJwTVm9E=,iv:BVB//Uc9nxGbbJg/63RfmE1PvU5eUQ0FdZiTh3b10Lk=,tag:KGc8JRH5F49PjdUvSOAC0Q==,type:str]
    version: 3.13.2
