apiVersion: v1
kind: Secret
metadata:
    name: registry-auth
    namespace: github-runner
type: Opaque
stringData:
    htpasswd: ENC[AES256_GCM,data:8p2S5cN/d5kzZXXnYuU1lotenJUvLyJu0OEalS5MBH1hCvJLx8A2eLmxYXK1AAdEvKM6wYXcpmGYBxxogFcsbyi3,iv:GhEk0WN9/gGo4eNymEiQl27WVH/H9WsKBJzTRhkCihk=,tag:25ZDtLtfUY8/6L8xytt5Jg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSXJENm5wa1VjZS9EWjJF
            Qmtud284NmF3SjdVYVF0UmQydDIyMFdqakhFCkIrRlBmd0lVb3VCVEtnVy9memkx
            ekp3ZXA2UnlxbStkTm5ZVENLcCtDcWcKLS0tIEtwWlNXMXJVUzdjWVIrelNtZUJu
            WElnNkFIYTFLSTQ1c2NuNk9GT3NqUmMKvypp4AxVAs8wfANIjgMKm69AQ4j6gBST
            f4C2Bf/jzf3UKBORoY/rVFkWieVDwqN2zqj04PLsA+MkdMrNUDkssg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19rz07h4nrfarqdm5fwucwj8024w2el04ak39nwrmdvjypjgukpsst5dmar
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T23:44:52Z"
    mac: ENC[AES256_GCM,data:OBOXO6jEeMAycuKaPX7FHaP8uEd35ZUh0wLpEKSSZEj4XTUdeCtgOZz21lM9h/hvHNcNP9cVLg2HFy1x6S3Y2OM1CJAfqWVN5Y0OW1v5N7803N3eZ2dopvk/1+A6v5/v2z79QcYrLFjEq5qa6Ul80fU2haTU4zD4EFT4Rb7Zfec=,iv:pOqvAyXBT31LlgZJUqnDbltrrpo/NLw0EvfTzT44dPU=,tag:qaBvYJm7LFxRR4+GGtRbuA==,type:str]
    version: 3.13.2
