apiVersion: v1
kind: Secret
metadata:
    name: registry-auth
    namespace: github-runner
type: Opaque
stringData:
    htpasswd: ENC[AES256_GCM,data:twILcN3uTEzyKMMHLQVOiARWuA2M3pwe2QFbT1dkBz/MHuWkxPLZDLDCFdVqGyPKoV2n0gsgM92PPvB00CJp7DJb6wdgv9qEnh9IwFfaJxpGu9HePNcQ2FyaO7EjtB3Bt2U7UrpbAc8hM2ZBg+C8WsXFBZHpnBUanCnUX64UEHGgQQyeYk+4cBIRj75n,iv:kmWIiFstmlRFP4zPqIb0doqKsshBwM0iNxKSI6Eid8s=,tag:XuTz8k6W0GuWggUTKnEPwg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSXJENm5wa1VjZS9EWjJF
            Qmtud284NmF3SjdVYVF0UmQydDIyMFdqakhFCkIrRlBmd0lVb3VCVEtnVy9memkx
            ekp3ZXA2UnlxbStkTm5ZVENLcCtDcWcKLS0tIEtwWlNXMXJVUzdjWVIrelNtZUJu
            WElnNkFIYTFLSTQ1c2NuNk9GT3NqUmMKvypp4AxVAs8wfANIjgMKm69AQ4j6gBST
            f4C2Bf/jzf3UKBORoY/rVFkWieVDwqN2zqj04PLsA+MkdMrNUDkssg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19rz07h4nrfarqdm5fwucwj8024w2el04ak39nwrmdvjypjgukpsst5dmar
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T02:48:33Z"
    mac: ENC[AES256_GCM,data:RVou2vja3wO04RxhbyBg6E3DZRi5rrzdl5J+LJYuBOQizBoEj+0xyf+cXv0Dz+Vy+G2y9fIv6UGtBCzyqnD9gfEqvoo2+wzy4CmhOR5/Dd2Hp0eEAgjGmCyYVRQ40cehsUklDXNzYwiq71McNEsvP45oXCZWAU+kFyGOhCUCmgI=,iv:7Ehb/tDOtH8WEtdPOxR5WQCwwsFjtZa39PYX5Row7T8=,tag:5a2bagbiTLc90AUlv9kkPA==,type:str]
    version: 3.13.2
