apiVersion: v1
kind: Secret
metadata:
    name: image-updater-registry
type: Opaque
stringData:
    auth: ENC[AES256_GCM,data:OUNPRIBpgWzr/1fv0Q63onJOrnYLXHlyVBtQ1wtlOeTcEiaXQJCxGvzNowx89w==,iv:nMUWiKbQAnXeBCLbRfEYHCn5cBss/KAIzXF/jQN4mu4=,tag:h2Q2HtWODqHI3K8bdbPyOg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VCtqZE5OdVVjN0w4QWNn
            aU9pMmZoKzNHQ0NPczVZMTYxTmRJTjFJSkVVClllK2ZyOUJxK0paZHF5M01mOXFz
            ejM5MXN4aW5sU2loTm9kbmhDdG9ZWkUKLS0tIENLdVFVMDNpRmFSU1lrMzNPWVpK
            ZW5BWXVQM2hhdXBFNEdQK3c4OHZZUWsKDdHIGn/LOEshmgAPDn7nxWGnkG0It/mn
            i08deRIvZn/8mZ7g/OrL3ek2JHqBhVHpNZ3TzBqGIMIIWjsQrbBt9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19rz07h4nrfarqdm5fwucwj8024w2el04ak39nwrmdvjypjgukpsst5dmar
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T02:51:32Z"
    mac: ENC[AES256_GCM,data:W+aDiua6QP+UYd0mRbzGt2Z2TVDjbNp8YV+1D2XpWLPFj48rAK5fh09vQHuiSiDKS1+djKUevQ1dkTp6jWCrOn3zKsYnYZ2zvkaPJyyRZPUN/dZXKZjUCk6csxO3KqfPnpOsEkSMvqIPSBphY74/0EP9Z9KkwYdM4kfNGm+tWV4=,iv:ap/hAEgrTW1Tgva/e8/qNQUWvgYY20woyfrgE6GpJbk=,tag:AcLad54hZ4IgeBY/sUfcfg==,type:str]
    version: 3.13.2
