apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: image-updater-secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - image-updater-registry.sops.yaml
